#InputLevel 1
AppsKey & a::SendEvent("{Text}ᚨ")
AppsKey & b::SendEvent("{Text}ᛒ")
AppsKey & c::SendEvent("{Text}ᚲ")
AppsKey & d::SendEvent("{Text}ᛞ")
AppsKey & e::SendEvent("{Text}ᛖ")
AppsKey & f::SendEvent("{Text}ᚠ")
AppsKey & g::SendEvent("{Text}ᚷ")
AppsKey & h::SendEvent("{Text}ᚺ")
AppsKey & i::SendEvent("{Text}ᛁ")
AppsKey & j::SendEvent("{Text}ᛃ")
AppsKey & k::SendEvent("{Text}ᚲ")
AppsKey & l::SendEvent("{Text}ᛚ")
AppsKey & m::SendEvent("{Text}ᛗ")
AppsKey & n::SendEvent("{Text}ᚾ")
AppsKey & o::SendEvent("{Text}ᛟ")
AppsKey & p::SendEvent("{Text}ᛈ")
AppsKey & r::SendEvent("{Text}ᚱ")
AppsKey & s::SendEvent("{Text}ᛊ")
AppsKey & t::SendEvent("{Text}ᛏ")
AppsKey & u::SendEvent("{Text}ᚢ")
AppsKey & w::SendEvent("{Text}ᚹ")
AppsKey & x::SendEvent("{Text}ᛦ")
AppsKey & y::SendEvent("{Text}ᚣ")
AppsKey & z::SendEvent("{Text}ᛉ")
AppsKey & [::SendEvent("{Text}∈")
AppsKey & ]::SendEvent("{Text}∋")
AppsKey & Space::SendEvent("☥") ;;Why? i Have no idea byt my friend ask for it! (hope there is no cursed context)
<^>![::SendEvent("{Text}⌘")
+<^>![::SendEvent("{Text}⌗")
<^>!]::SendEvent("{Text}⌨")
+<^>!]::SendEvent("{Text}⌂")
<^>!\::SendEvent("{Text}ℵ")
+<^>!\::SendEvent("{Text}⌬")
<^>!1::SendEvent("{Text}¬")
<^>!2::SendEvent("{Text}©")
+<^>!2::SendEvent("{Text}®")
+<^>!3::SendEvent("{Text}𐂠")
<^>!3::SendEvent("{Text}°")
<^>!4::SendEvent("{Text}£")
+<^>!4::SendEvent("{Text}¥")
<^>!5::SendEvent("{Text}⅓")
+<^>!5::SendEvent("{Text}⅐")
<^>!6::SendEvent("{Text}∧")
+<^>!6::SendEvent("{Text}λ")
<^>!7::SendEvent("{Text}∞")
+<^>!7::SendEvent("{Text}µ")
<^>!8::SendEvent("{Text}·")
<^>!9::SendEvent("{Text}ↄ")
+<^>!9::SendEvent("{Text}⌒")
<^>!0::SendEvent("{Text}Ↄ")
+<^>!0::SendEvent("{Text}⌣")
+<^>!`::SendEvent("{Text}∽")
<^>!`::SendEvent("{Text}´")
<^>!-::SendEvent("{Text}‾")
+<^>!-::SendEvent("{Text}≺")  
<^>!=::SendEvent("{Text}×")
+<^>!=::SendEvent("{Text}≻")
<^>!,::SendEvent("{Text}¸")
<^>!/::SendEvent("{Text}÷")
Numpad0::SendEvent("{Text}∅")
Numpad5::SendEvent("{Text}§")
NumpadDiv::SendEvent("{Text}⁄")  
#InputLevel 